```{r}
library(InteractionSet)
library(Biostrings)
library(BSgenome.Hsapiens.UCSC.hg38)
library(tidyverse)
library("R.utils")
library(GenomicInteractions)
```

```{r}
make_ginteractions_from_df = function(df, extra_cols = NULL){
  
  gr1 = df |> 
    dplyr::select(seqnames1, start1, end1, all_of(extra_cols)) |> 
    makeGRangesFromDataFrame(seqnames = 'seqnames1', start.field = 'start1', end.field = 'end1',
                             keep.extra.columns = TRUE)
  gr2 = makeGRangesFromDataFrame(df, seqnames = 'seqnames2', start.field = 'start2', end.field = 'end2')
  
  GInteractions(gr1, gr2)
}

annotate_CREs = function(gi, cre, cre_name, extend=FALSE){
  
  if (extend != FALSE){
    # Extend anchor1
    anchor_one = resize(anchorOne(gi), width = width(anchorOne(gi)) + extend, fix = "center")
    
    # Extend anchor2 
    anchor_two = resize(anchorTwo(gi), width = width(anchorTwo(gi)) + extend, fix = "center")
    
    updated_gi = GInteractions(anchor_one, anchor_two)
    
  } else {
    updated_gi = gi
  }
  
  overlap1 = InteractionSet::findOverlaps(updated_gi, cre, use.region="first")
  overlap2 = InteractionSet::findOverlaps(updated_gi, cre, use.region="second")
  
  anchor1 = as_tibble(gi[queryHits(overlap1)]) |> 
    dplyr::select(-contains('width'), -contains('strand')) |>
    mutate(anch1_anno = cre_name) |> 
    distinct()
  
  anchor2 = as_tibble(gi[queryHits(overlap2)]) |> 
    dplyr::select(-contains('width'), -contains('strand')) |>
    mutate(anch2_anno = cre_name) |> 
    distinct()
  
  full_join(anchor1, anchor2)
}

annotate_loop_classes = function(loops, cCREs, extend=FALSE){
  
  names(cCREs) |> 
    map(~annotate_CREs(loops, cCREs[[.x]], .x, extend=extend)) |> 
    purrr::reduce(full_join, by = c('seqnames1', 'start1', 'end1', 'seqnames2', 'start2', 'end2', 'name')) |>
    full_join(as_tibble(loops) |>
                dplyr::select('seqnames1', 'start1', 'end1', 'seqnames2', 'start2', 'end2', 'name')) |>
    mutate(selected_anch1 = case_when(
      anch1_anno.y == 'promoter' ~ 'promoter',
      anch1_anno.x == 'enhancer' ~ 'enhancer',
      anch1_anno == 'CTCF' ~ 'CTCF',
      # anch1_anno.x.x == 'polycomb' ~ 'polycomb',
      # anch1_anno.y.y == 'CTCF' ~ 'CTCF',
      TRUE ~ 'NA'
    ), selected_anch2 = case_when(
      anch2_anno.y == 'promoter' ~ 'promoter',
      anch2_anno.x == 'enhancer' ~ 'enhancer',
      anch2_anno == 'CTCF' ~ 'CTCF',
      TRUE ~ 'NA'
    )) |>
    dplyr::select(-contains('anno')) |>
    mutate(loop_class = case_when(
      selected_anch1 == 'enhancer' & selected_anch2 == 'promoter' ~ 'E-P',
      selected_anch1 == 'promoter' & selected_anch2 == 'enhancer' ~ 'E-P',
      selected_anch1 == 'promoter' & selected_anch2 == 'promoter' ~ 'P-P',
      selected_anch1 == 'enhancer' & selected_anch2 == 'enhancer' ~ 'E-E',
      selected_anch1 == 'promoter' | selected_anch2 == 'promoter' ~ 'E/P-other',
      selected_anch1 == 'enhancer' | selected_anch2 == 'enhancer' ~ 'E/P-other',
      selected_anch1 == 'CTCF' & selected_anch2 == 'CTCF' ~ 'CTCF-CTCF',
      selected_anch1 == 'CTCF' | selected_anch2 == 'CTCF' ~ 'CTCF-other',
      TRUE ~ 'other-other'
    ))
}

write_seqs = function(things, filename, gi=FALSE){
  if (gi == TRUE){
    seqs = getSeq(BSgenome.Hsapiens.UCSC.hg38, get_anchors_from_interactions(things))
  } else {
    seqs = getSeq(BSgenome.Hsapiens.UCSC.hg38, things)
  }
  names(seqs) = paste0('CRE_anchor_', c(1:length(seqs)))
  writeXStringSet(seqs, filename)
}

get_anchors_from_interactions = function(df, extend=FALSE){
  
  anchor1_df = df |> 
    dplyr::select(-seqnames2, -start2, -end2) |> 
    dplyr::rename(seqnames = seqnames1, start = start1, end = end1)
  
  anchor2_df = df |> 
    dplyr::select(-seqnames1, -start1, -end1) |> 
    dplyr::rename(seqnames = seqnames2, start = start2, end = end2)
  
  if (extend==FALSE){
    anchors = bind_rows(anchor1_df, anchor2_df) |> 
      distinct(seqnames, start, end) |>
      makeGRangesFromDataFrame()
  } else {
    anchors = bind_rows(anchor1_df, anchor2_df) |> 
      distinct(seqnames, start, end) |>
      mutate(start = start - extend, end = end + extend) |> 
      makeGRangesFromDataFrame()
  }
}
```

```{r}
DATAPATH <- '/Users/varshiniramanathan/Documents/fracshift_data'
GM12878_cCREs <- readRDS(file.path(DATAPATH, 'GM12878_cCREs.rds'))
```

```{r}

GM12878_loops_200bp_GI = read_tsv(file.path(DATAPATH, 'GM12878_deep_calls_uniq.txt')) |> 
  dplyr::rename(seqnames1 = chr1, center1 = start1, center2 = end1) |> 
  mutate(seqnames2 = seqnames1, start1 = center1 - 100, end1 = center1 + 100,
         start2 = center2 - 100, end2 = center2 + 100) |> 
  make_ginteractions_from_df() 

# this generates supp. fig s6b second plot using the union set of chiron and mustache calls
GM12878_fracshift_200bp_loops_GI = read_tsv(file.path(DATAPATH, 'chiron_within_mus.bedpe')) |> 
  dplyr::rename(seqnames1 = chr1, center1 = start1, center2 = end1) |> 
  mutate(seqnames2 = seqnames1, start1 = center1 - 100, end1 = center1 + 100,
         start2 = center2 - 100, end2 = center2 + 100) |> 
  make_ginteractions_from_df() 

GM12878_mustache_200bp_loops_GI = read_tsv(file.path(DATAPATH, 'mus_within_chiron.bedpe')) |> 
  dplyr::rename(seqnames1 = chr1, center1 = start1, center2 = end1) |> 
  mutate(seqnames2 = seqnames1, start1 = center1 - 100, end1 = center1 + 100,
         start2 = center2 - 100, end2 = center2 + 100) |> 
  make_ginteractions_from_df() 

# s6c first plot is generated by using all chiron loop calls and mustache loop calls from the first 5 regions
GM12878_fracshift_200bp_5loops_GI = read_tsv(file.path(DATAPATH, 'GM12878_loops_fracshift_200_mask3.txt')) |> 
  dplyr::rename(seqnames1 = chr1, center1 = start1, center2 = end1) |> 
  mutate(seqnames2 = seqnames1, start1 = center1 - 100, end1 = center1 + 100,
         start2 = center2 - 100, end2 = center2 + 100) |> 
  make_ginteractions_from_df() 

GM12878_mustache_200bp_5loops_GI = read_tsv(file.path(DATAPATH, 'mustache_5regions_q0.02.bed')) |> 
  dplyr::rename(seqnames1 = chr1, center1 = start1, center2 = end1) |> 
  mutate(seqnames2 = seqnames1, start1 = center1 - 100, end1 = center1 + 100,
         start2 = center2 - 100, end2 = center2 + 100) |> 
  make_ginteractions_from_df() 

```

```{r}
kheradpour_ctcf_motifs = read_tsv(file.path(DATAPATH, 'CTCF_known1_matches_hg38.bed'), col_names = c('chrom', 'start', 'end', 'strand'), show_col_types = FALSE) |> 
  makeGRangesFromDataFrame()
```

### Filter CTCF ChIP by CTCF_motifs 
```{r}
GM12878_CTCF_ChIP = read_tsv(file.path(DATAPATH, 'GM12878_real_chip.bed.gz'),
                             col_names = c('chrom', 'start', 'end', paste0('crap', c(1:3)), 'score', 'crap4', 'crap5', 'summit'), show_col_types = FALSE) |> 
  mutate(summit_coord = start + summit) |> 
  select('chrom', 'start', 'end', 'score', 'summit_coord') |> 
  makeGRangesFromDataFrame(keep.extra.columns = TRUE) 

kheradpour_ctcf_motifs = read_tsv(file.path(DATAPATH, 'CTCF_known1_matches_hg38.bed'), col_names = c('chrom', 'start', 'end', 'strand'), show_col_types = FALSE) |> 
  makeGRangesFromDataFrame()
```

```{r}
GM12878_CTCF_ChIP_kheradpour_subset = subsetByOverlaps(GM12878_CTCF_ChIP, kheradpour_ctcf_motifs)
```

```{r}
GM12878_loops_200bp_CTCF_motif_anchored = annotate_CREs(GM12878_loops_200bp_GI, GM12878_CTCF_ChIP_kheradpour_subset, 'CTCF', extend=1800) |> 
  filter(anch1_anno == 'CTCF' & anch2_anno == 'CTCF')

GM12878_loops_200bp_fracshift_updated_CTCF_motif_anchored = annotate_CREs(GM12878_fracshift_200bp_loops_GI, GM12878_CTCF_ChIP_kheradpour_subset, 'CTCF', extend=1800) |> 
  filter(anch1_anno == 'CTCF' & anch2_anno == 'CTCF')

GM12878_loops_200bp_mustache_updated_CTCF_motif_anchored = annotate_CREs(GM12878_mustache_200bp_loops_GI, GM12878_CTCF_ChIP_kheradpour_subset, 'CTCF', extend=1800) |> 
  filter(anch1_anno == 'CTCF' & anch2_anno == 'CTCF')

GM12878_loops_200bp_fracshift_5regions_CTCF_motif_anchored = annotate_CREs(GM12878_fracshift_200bp_5loops_GI, GM12878_CTCF_ChIP_kheradpour_subset, 'CTCF', extend=1800) |> 
  filter(anch1_anno == 'CTCF' & anch2_anno == 'CTCF')

GM12878_loops_200bp_mustache_5regions_CTCF_motif_anchored = annotate_CREs(GM12878_mustache_200bp_5loops_GI, GM12878_CTCF_ChIP_kheradpour_subset, 'CTCF', extend=1800) |> 
  filter(anch1_anno == 'CTCF' & anch2_anno == 'CTCF')

```

### Plot enrichment of peak summits rather than peaks directly 

```{r}
annotate_summits = function(anchors, chip, final_width=2000){
  
  anchors = resize(get_anchors_from_interactions(anchors), width = final_width, fix = 'center')
  
  overlap = findOverlaps(anchors, chip)
  as_tibble(anchors[queryHits(overlap)]) |> 
    select(-width, -strand) |> 
    bind_cols(as_tibble(chip[subjectHits(overlap)]) |> select(summit_coord))
}
```
# for all 3 compared in first 5 regions
```{r}
data <- annotate_summits(GM12878_loops_200bp_CTCF_motif_anchored, GM12878_CTCF_ChIP) |> 
  mutate(correction = 'manual annotation') |> 
  bind_rows(annotate_summits(GM12878_loops_200bp_fracshift_5regions_CTCF_motif_anchored, GM12878_CTCF_ChIP) |> mutate(correction = 'manual annotation + fracshift')) |> 
  bind_rows(annotate_summits(GM12878_loops_200bp_mustache_5regions_CTCF_motif_anchored, GM12878_CTCF_ChIP) |> 
              mutate(correction = 'mustache')) |> 
  mutate(summit_offset = summit_coord - ((start + end)/2)) 
ggplot(data, aes(abs(summit_offset), col = correction)) +
  #geom_histogram(aes(y = ..density.., fill=correction), position='identity', bins=10, alpha=0.2) +
  #geom_density(linewidth=1)+
  stat_ecdf() +
  theme_classic() + 
  scale_color_manual(values = c("manual annotation" = "#0077BB", "manual annotation + fracshift" = "#EE7733", "mustache"="#009988")) +
  scale_x_continuous(expand = c(0, 0), limits = c(0,NA)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(element_line(linewidth=1),
        axis.text.x = element_text(size = 14,  color = "black"),  # X-tick labels font size
        axis.text.y = element_text(size = 14,  color = "black"),  # Y-tick labels font size
        axis.title.x = element_text(size = 16,  color = "black"), # X-axis label font size
        axis.title.y = element_text(size = 16,  color = "black")) + #+ 
  xlab("loop center offset from CTCF ChIP summit (bp)") +
  ylab("density") 
grouped_medians = aggregate(abs(data$summit_offset), list(data$correction), FUN=median)

```

# for comparing chiron and mustache in all 14 regions 
```{r}
data <- 
  bind_rows(annotate_summits(GM12878_loops_200bp_fracshift_updated_CTCF_motif_anchored, GM12878_CTCF_ChIP) |> mutate(correction = 'chiron + fracshift')) |> 
  bind_rows(annotate_summits(GM12878_loops_200bp_mustache_updated_CTCF_motif_anchored, GM12878_CTCF_ChIP) |> 
              mutate(correction = 'mustache')) |> 
  mutate(summit_offset = summit_coord - ((start + end)/2)) 
ggplot(data, aes(abs(summit_offset), col = correction)) +
  #geom_histogram(aes(y = ..density.., fill=correction), position='identity', bins=10, alpha=0.2) +
  #geom_density(linewidth=1)+
  stat_ecdf() +
  theme_classic() + 
  scale_color_manual(values = c( "chiron + fracshift" = "#EE7733", "mustache"="#009988")) +
  scale_x_continuous(expand = c(0, 0), limits = c(0,NA)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(element_line(linewidth=1),
        axis.text.x = element_text(size = 14,  color = "black"),  # X-tick labels font size
        axis.text.y = element_text(size = 14,  color = "black"),  # Y-tick labels font size
        axis.title.x = element_text(size = 16,  color = "black"), # X-axis label font size
        axis.title.y = element_text(size = 16,  color = "black")) + #+ 
  xlab("loop center offset from CTCF ChIP summit (bp)") +
  ylab("density") 
#ggsave(file.path(DATAPATH, 'frac_v2.svg'), img, width=8, height=5.5)

grouped_medians_all = aggregate(abs(data$summit_offset), list(data$correction), FUN=median)

```

